version: '3.8'

volumes:
  contatoDB:

networks:
  contatoNET:

services:

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: contatoDB
    ports:
      - "1433:1433"
    volumes:
      - contatoDB:/var/lib/sqlserver
    networks:
      - contatoNET
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: numsey#2021
      MSSQL_PID: EXPRESS